require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LabelsController do

  # This should return the minimal set of attributes required to create a valid
  # Label. As you add validations to Label, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LabelsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all labels as @labels" do
      label = Label.create! valid_attributes
      get :index, {}, valid_session
      assigns(:labels).should eq([label])
    end
  end

  describe "GET show" do
    it "assigns the requested label as @label" do
      label = Label.create! valid_attributes
      get :show, {:id => label.to_param}, valid_session
      assigns(:label).should eq(label)
    end
  end

  describe "GET new" do
    it "assigns a new label as @label" do
      get :new, {}, valid_session
      assigns(:label).should be_a_new(Label)
    end
  end

  describe "GET edit" do
    it "assigns the requested label as @label" do
      label = Label.create! valid_attributes
      get :edit, {:id => label.to_param}, valid_session
      assigns(:label).should eq(label)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Label" do
        expect {
          post :create, {:label => valid_attributes}, valid_session
        }.to change(Label, :count).by(1)
      end

      it "assigns a newly created label as @label" do
        post :create, {:label => valid_attributes}, valid_session
        assigns(:label).should be_a(Label)
        assigns(:label).should be_persisted
      end

      it "redirects to the created label" do
        post :create, {:label => valid_attributes}, valid_session
        response.should redirect_to(Label.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved label as @label" do
        # Trigger the behavior that occurs when invalid params are submitted
        Label.any_instance.stub(:save).and_return(false)
        post :create, {:label => {}}, valid_session
        assigns(:label).should be_a_new(Label)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Label.any_instance.stub(:save).and_return(false)
        post :create, {:label => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested label" do
        label = Label.create! valid_attributes
        # Assuming there are no other labels in the database, this
        # specifies that the Label created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Label.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => label.to_param, :label => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested label as @label" do
        label = Label.create! valid_attributes
        put :update, {:id => label.to_param, :label => valid_attributes}, valid_session
        assigns(:label).should eq(label)
      end

      it "redirects to the label" do
        label = Label.create! valid_attributes
        put :update, {:id => label.to_param, :label => valid_attributes}, valid_session
        response.should redirect_to(label)
      end
    end

    describe "with invalid params" do
      it "assigns the label as @label" do
        label = Label.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Label.any_instance.stub(:save).and_return(false)
        put :update, {:id => label.to_param, :label => {}}, valid_session
        assigns(:label).should eq(label)
      end

      it "re-renders the 'edit' template" do
        label = Label.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Label.any_instance.stub(:save).and_return(false)
        put :update, {:id => label.to_param, :label => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested label" do
      label = Label.create! valid_attributes
      expect {
        delete :destroy, {:id => label.to_param}, valid_session
      }.to change(Label, :count).by(-1)
    end

    it "redirects to the labels list" do
      label = Label.create! valid_attributes
      delete :destroy, {:id => label.to_param}, valid_session
      response.should redirect_to(labels_url)
    end
  end

end
