require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LendersController do

  # This should return the minimal set of attributes required to create a valid
  # Lender. As you add validations to Lender, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LendersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lenders as @lenders" do
      lender = Lender.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lenders).should eq([lender])
    end
  end

  describe "GET show" do
    it "assigns the requested lender as @lender" do
      lender = Lender.create! valid_attributes
      get :show, {:id => lender.to_param}, valid_session
      assigns(:lender).should eq(lender)
    end
  end

  describe "GET new" do
    it "assigns a new lender as @lender" do
      get :new, {}, valid_session
      assigns(:lender).should be_a_new(Lender)
    end
  end

  describe "GET edit" do
    it "assigns the requested lender as @lender" do
      lender = Lender.create! valid_attributes
      get :edit, {:id => lender.to_param}, valid_session
      assigns(:lender).should eq(lender)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lender" do
        expect {
          post :create, {:lender => valid_attributes}, valid_session
        }.to change(Lender, :count).by(1)
      end

      it "assigns a newly created lender as @lender" do
        post :create, {:lender => valid_attributes}, valid_session
        assigns(:lender).should be_a(Lender)
        assigns(:lender).should be_persisted
      end

      it "redirects to the created lender" do
        post :create, {:lender => valid_attributes}, valid_session
        response.should redirect_to(Lender.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lender as @lender" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lender.any_instance.stub(:save).and_return(false)
        post :create, {:lender => {}}, valid_session
        assigns(:lender).should be_a_new(Lender)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lender.any_instance.stub(:save).and_return(false)
        post :create, {:lender => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lender" do
        lender = Lender.create! valid_attributes
        # Assuming there are no other lenders in the database, this
        # specifies that the Lender created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lender.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lender.to_param, :lender => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lender as @lender" do
        lender = Lender.create! valid_attributes
        put :update, {:id => lender.to_param, :lender => valid_attributes}, valid_session
        assigns(:lender).should eq(lender)
      end

      it "redirects to the lender" do
        lender = Lender.create! valid_attributes
        put :update, {:id => lender.to_param, :lender => valid_attributes}, valid_session
        response.should redirect_to(lender)
      end
    end

    describe "with invalid params" do
      it "assigns the lender as @lender" do
        lender = Lender.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lender.any_instance.stub(:save).and_return(false)
        put :update, {:id => lender.to_param, :lender => {}}, valid_session
        assigns(:lender).should eq(lender)
      end

      it "re-renders the 'edit' template" do
        lender = Lender.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lender.any_instance.stub(:save).and_return(false)
        put :update, {:id => lender.to_param, :lender => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lender" do
      lender = Lender.create! valid_attributes
      expect {
        delete :destroy, {:id => lender.to_param}, valid_session
      }.to change(Lender, :count).by(-1)
    end

    it "redirects to the lenders list" do
      lender = Lender.create! valid_attributes
      delete :destroy, {:id => lender.to_param}, valid_session
      response.should redirect_to(lenders_url)
    end
  end

end
