require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProspectivePropertiesController do

  # This should return the minimal set of attributes required to create a valid
  # ProspectiveProperty. As you add validations to ProspectiveProperty, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProspectivePropertiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prospective_properties as @prospective_properties" do
      prospective_property = ProspectiveProperty.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prospective_properties).should eq([prospective_property])
    end
  end

  describe "GET show" do
    it "assigns the requested prospective_property as @prospective_property" do
      prospective_property = ProspectiveProperty.create! valid_attributes
      get :show, {:id => prospective_property.to_param}, valid_session
      assigns(:prospective_property).should eq(prospective_property)
    end
  end

  describe "GET new" do
    it "assigns a new prospective_property as @prospective_property" do
      get :new, {}, valid_session
      assigns(:prospective_property).should be_a_new(ProspectiveProperty)
    end
  end

  describe "GET edit" do
    it "assigns the requested prospective_property as @prospective_property" do
      prospective_property = ProspectiveProperty.create! valid_attributes
      get :edit, {:id => prospective_property.to_param}, valid_session
      assigns(:prospective_property).should eq(prospective_property)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProspectiveProperty" do
        expect {
          post :create, {:prospective_property => valid_attributes}, valid_session
        }.to change(ProspectiveProperty, :count).by(1)
      end

      it "assigns a newly created prospective_property as @prospective_property" do
        post :create, {:prospective_property => valid_attributes}, valid_session
        assigns(:prospective_property).should be_a(ProspectiveProperty)
        assigns(:prospective_property).should be_persisted
      end

      it "redirects to the created prospective_property" do
        post :create, {:prospective_property => valid_attributes}, valid_session
        response.should redirect_to(ProspectiveProperty.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prospective_property as @prospective_property" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveProperty.any_instance.stub(:save).and_return(false)
        post :create, {:prospective_property => {}}, valid_session
        assigns(:prospective_property).should be_a_new(ProspectiveProperty)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveProperty.any_instance.stub(:save).and_return(false)
        post :create, {:prospective_property => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prospective_property" do
        prospective_property = ProspectiveProperty.create! valid_attributes
        # Assuming there are no other prospective_properties in the database, this
        # specifies that the ProspectiveProperty created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProspectiveProperty.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => prospective_property.to_param, :prospective_property => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested prospective_property as @prospective_property" do
        prospective_property = ProspectiveProperty.create! valid_attributes
        put :update, {:id => prospective_property.to_param, :prospective_property => valid_attributes}, valid_session
        assigns(:prospective_property).should eq(prospective_property)
      end

      it "redirects to the prospective_property" do
        prospective_property = ProspectiveProperty.create! valid_attributes
        put :update, {:id => prospective_property.to_param, :prospective_property => valid_attributes}, valid_session
        response.should redirect_to(prospective_property)
      end
    end

    describe "with invalid params" do
      it "assigns the prospective_property as @prospective_property" do
        prospective_property = ProspectiveProperty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveProperty.any_instance.stub(:save).and_return(false)
        put :update, {:id => prospective_property.to_param, :prospective_property => {}}, valid_session
        assigns(:prospective_property).should eq(prospective_property)
      end

      it "re-renders the 'edit' template" do
        prospective_property = ProspectiveProperty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProspectiveProperty.any_instance.stub(:save).and_return(false)
        put :update, {:id => prospective_property.to_param, :prospective_property => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prospective_property" do
      prospective_property = ProspectiveProperty.create! valid_attributes
      expect {
        delete :destroy, {:id => prospective_property.to_param}, valid_session
      }.to change(ProspectiveProperty, :count).by(-1)
    end

    it "redirects to the prospective_properties list" do
      prospective_property = ProspectiveProperty.create! valid_attributes
      delete :destroy, {:id => prospective_property.to_param}, valid_session
      response.should redirect_to(prospective_properties_url)
    end
  end

end
